name: chatapp
description: "Chat App Flutter Firebase project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.9.0
  another_flutter_splash_screen: ^1.2.1
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  flutter_signin_button: ^2.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  intl: ^0.20.1
  logger: ^2.5.0
  device_info_plus: ^11.2.0
  network_info_plus: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
