// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ7U_TJoJlBW1ODygRSqb-KdK14wcTMaM',
    appId: '1:461747309251:web:a598e4b5ee45c332a9f076',
    messagingSenderId: '461747309251',
    projectId: 'flutter-app-3466d',
    authDomain: 'flutter-app-3466d.firebaseapp.com',
    storageBucket: 'flutter-app-3466d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDshEOzBRWRkveEX5uZy0si4jxkRVnO7Qc',
    appId: '1:461747309251:android:13ebe14dec44728ca9f076',
    messagingSenderId: '461747309251',
    projectId: 'flutter-app-3466d',
    storageBucket: 'flutter-app-3466d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiev0YIQn2p8SWJSACd7Mapl8mllHMbw0',
    appId: '1:461747309251:ios:b47cfb6b6900395ca9f076',
    messagingSenderId: '461747309251',
    projectId: 'flutter-app-3466d',
    storageBucket: 'flutter-app-3466d.firebasestorage.app',
    iosClientId: '461747309251-bt2ofbr8m2ehv1ttpl8p4s194arrgdc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiev0YIQn2p8SWJSACd7Mapl8mllHMbw0',
    appId: '1:461747309251:ios:b47cfb6b6900395ca9f076',
    messagingSenderId: '461747309251',
    projectId: 'flutter-app-3466d',
    storageBucket: 'flutter-app-3466d.firebasestorage.app',
    iosClientId: '461747309251-bt2ofbr8m2ehv1ttpl8p4s194arrgdc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ7U_TJoJlBW1ODygRSqb-KdK14wcTMaM',
    appId: '1:461747309251:web:4a1f5d124ceb8ab7a9f076',
    messagingSenderId: '461747309251',
    projectId: 'flutter-app-3466d',
    authDomain: 'flutter-app-3466d.firebaseapp.com',
    storageBucket: 'flutter-app-3466d.firebasestorage.app',
  );

}